### ISSUE TITLE
咨询关于文章的问题

### ISSUE THREAD

**Issue by hao12liu** [yu-yang-sjtu/Determine-the-initial-structure-of-c-LLZO#1]
尊敬的于洋博士：
您好，很抱歉打扰您！

我叫刘志浩，是中国江苏省南京市南京工业大学的研究生。我读了您的论文《Activating the paddle-wheel effect towards lower temperature in a new sodium-ion solid electrolyte, Na3.5Si0.5P0.5Se4》，遇到了一些问题，希望您能给我一些帮助。

我对文章中的“Fig. 3 (b) SiSe4 重定向自相关函数 C(t)。”和“Fig. 5（a）SiSe4的角速度自相关的傅立叶变换计算的功率谱，(b)SiSe4的旋转扩散率”非常感兴趣。
主要是文章中描述阴离子旋转的重定向自相关函数C(t)，以及在文章中利用阴离子旋转的角度自相关函数计算的功率谱和旋转扩散率。（这几个部分的图片我都附在下面。）

我想在我的结果文件中分析Na离子和阴离子旋转之间的相关性。我发现您的方法非常清晰直观，所以我想参考您的文章中描述的阴阳离子之间相关性的判断方法，以及阴离子基团C(t)和功率谱的计算方法。
您的方法应该是一种很新颖的方法，我在github里找到了很多论文和很多代码，发现最多只能找到判断阴离子角位移的方法，对于阴离子团的功率谱和扩散系数的计算几乎没有，所以我只能希望您能给我一些帮助，请您能够帮助我。

目前我只能分析Na（单个离子）的平移和速度自相关函数以及功率谱。我不知道如何分析由多个原子组成的阴离子基团的功率谱和文中提到的重定向自相关函数C (t)。我不知道该如何进行这些分析，希望得到您的帮助。

1.请问图3中描述阴离子旋转的重定向自相关函数C(t)是如何通过处理VASP轨迹文件获得的？ 

2.对阴离子基团的角位移的分析是考虑整个四面体还是考虑单个Si—Se键呢？

3.如何对轨迹文件进行处理才能得到文章中提到的SiSe4阴离子基团的功率谱和扩散系数呢？

如果代码是公开的，你能给我看看你的源代码吗？如果不公开的话，你能给我一个大概的想法吗？

我的邮箱是zhihao@njtech.edu.cn

期待您的回复，非常感谢！
祝您科研顺利！
刘志浩
![Fig  3 Effect of temperature on Na diffusion and SiSe4 reorientationrotation in Na4SiSe4](https://github.com/yu-yang-sjtu/Determine-the-initial-structure-of-c-LLZO/assets/132411682/d4fe0421-456d-417b-8c8b-c5ddc71b195b)
![fig5 SiSe4 angular veloration ](https://github.com/yu-yang-sjtu/Determine-the-initial-structure-of-c-LLZO/assets/132411682/e7c050f5-e238-4cf4-8b02-6450fba14ff2)

**Comment by yu-yang-sjtu** [comment]
你好,  代码目前是不公开的。
第一个问题和第三个问题在文章的Methods部分有对应的公式及说明
第二个问题角位移的分析是考虑的单个Si-Se键
如果需要进一步讨论可以加我微信18328531127
